/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */

import { GenericContractsDeclaration } from "../lib/contract";

const deployedContracts: GenericContractsDeclaration = {
  10143: {
    VWAPDemo: {
      address: "0xBbf65AA24Ba6826A0872E3122bD74731e22b63f8",
      abi: [
        {
          inputs: [],
          name: "InvalidSlice",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidSlices",
          type: "error",
        },
        {
          inputs: [],
          name: "Max20Slices",
          type: "error",
        },
        {
          inputs: [],
          name: "NotCreator",
          type: "error",
        },
        {
          inputs: [],
          name: "OrderNotActive",
          type: "error",
        },
        {
          inputs: [],
          name: "SliceAlreadyExecuted",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "orderId",
              type: "bytes32",
            },
          ],
          name: "OrderCompleted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "orderId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "slices",
              type: "uint8",
            },
          ],
          name: "OrderCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "orderId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "sliceIndex",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "executor",
              type: "address",
            },
          ],
          name: "SliceExecuted",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "numSlices",
              type: "uint8",
            },
          ],
          name: "createOrder",
          outputs: [
            {
              internalType: "bytes32",
              name: "orderId",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "orderId",
              type: "bytes32",
            },
            {
              internalType: "uint8",
              name: "sliceIndex",
              type: "uint8",
            },
          ],
          name: "executeSlice",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "orderId",
              type: "bytes32",
            },
          ],
          name: "getExecutedMask",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "orderId",
              type: "bytes32",
            },
          ],
          name: "getOrder",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "creator",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "totalAmount",
                  type: "uint256",
                },
                {
                  internalType: "uint8",
                  name: "numSlices",
                  type: "uint8",
                },
                {
                  internalType: "uint8",
                  name: "executedSlices",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "startTime",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "active",
                  type: "bool",
                },
              ],
              internalType: "struct VWAPDemo.Order",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "orderId",
              type: "bytes32",
            },
            {
              internalType: "uint8",
              name: "sliceIndex",
              type: "uint8",
            },
          ],
          name: "isSliceExecuted",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "orders",
          outputs: [
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "totalAmount",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "numSlices",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "executedSlices",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "startTime",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "sliceSizes",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
};

export default deployedContracts;
